<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="representation" nsURI="http://www.dlr.de/ft/premise/representation/2012/"
    nsPrefix="rep">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The representations package includes all model elements for graphic description of systems."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Representation" eSuperTypes="PREMISE_Element.ecore#//AExtension PREMISE_Registry.ecore#//AVersionedModelRoot">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The representation describes the elements to be used for the graphic representation of systems. For this purpose a file is used that contains the description. This is set with a PREMISE model in relationship and evaluated by graphical exporter like architecture or state diagram exporter."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectors" upperBound="-1"
        eType="#//Selector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selector" eSuperTypes="PREMISE_Registry.ecore#//ANameItem">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The Selector uses an OCL-Query to select elements that should be decorated with the associated decorators."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceSelector" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorators" upperBound="-1"
        eType="#//ADecorator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADecorator" abstract="true" eSuperTypes="PREMISE_Registry.ecore#//ANameItem">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Is an abstract model element for a decorative element."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color" eSuperTypes="#//ADecorator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Is a model element to provide a color in the format #00FF00 (for green)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeShape" eSuperTypes="#//ADecorator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes the shape of a node element. By default, a rectangle shape with a height and width is used."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coordinate" eSuperTypes="#//ADecorator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes the position of a node element with an x and y coordinate."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineStyle" eSuperTypes="#//ADecorator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes the representation of the node edge or edge with a line style and a line width."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//StyleTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelStyle" eSuperTypes="#//ADecorator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes the representation of the node or edge label with typical font attributes and visibility."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontStyle" eType="#//FontStyle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="underlined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StyleTypes">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Includes all allowed line styles."/>
    </eAnnotations>
    <eLiterals name="Line" literal="LINE"/>
    <eLiterals name="Dashed" value="1" literal="DASHED"/>
    <eLiterals name="Dotted" value="2" literal="DOTTED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FontStyle">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Includes all allowed font styles."/>
    </eAnnotations>
    <eLiterals name="Plain" literal="PLAIN"/>
    <eLiterals name="Bold" value="1" literal="BOLD"/>
    <eLiterals name="Italic" value="2" literal="ITALIC"/>
    <eLiterals name="BoldItalic" value="3" literal="BOLDITALIC"/>
  </eClassifiers>
</ecore:EPackage>
