<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="registry" nsURI="http://www.dlr.de/ft/premise/registry/2010/"
    nsPrefix="reg">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The package registry contains all model elements to the description of lists of global definitions. These may be, for example, units and constants."/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="graph" value="PREMISE_Graph.ecore#/"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Registry" eSuperTypes="#//ANameItem #//AVersionedModelRoot">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The registry contains lists of global definitions of disciplines, units, constants."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" upperBound="-1"
        eType="#//Unit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="#//Constant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaTypes" upperBound="-1"
        eType="#//MetaTypeDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANameItem" abstract="true" eSuperTypes="#//IPremiseObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="All elements which shall have a name inherits from this abstract class."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADataItem" abstract="true" eSuperTypes="#//ANameItem">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="All elements which shall have a identification number and shall have notifications inherits from this abstract data item."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" ordered="false"
        upperBound="-1" eType="#//Note" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="#//IPremiseObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Discribes a notification. The notification includes a message text the author and the date of origin."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" ordered="false"
        upperBound="-1" eType="#//Note" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaData" eSuperTypes="#//IPremiseObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A MetaData item describes a name value pair of an untyped data element. To create a meta data hierarchy, meta data can contain meta data as child elements in their metaData reference."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit" eSuperTypes="#//ANameItem">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A standardized quantity of measurement of a physical quantity. The use of SI units shall be prefered."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SymbolUnique"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="SymbolUnique" value="Tuple {&#xA;&#x9;message : String = &#xA;&#x9;&#x9;&#x9;let duplicateStr = Unit.allInstances()->excluding(self)->select(other | other.symbol = self.symbol)&#xA;&#x9;&#x9;&#x9;&#x9;->collect(name + ' (Registry &quot;' + oclContainer.oclAsType(Registry).name +'&quot;)')&#xA;&#x9;&#x9;&#x9;&#x9;->iterate(n; res : String='' | res + '  ' + n)&#xA;&#x9;&#x9;&#x9;&#x9;.trim()&#xA;&#x9;&#x9;&#x9;&#x9;.substituteAll('  ', ', ')&#xA;&#x9;&#x9;&#x9;in &#xA;&#x9;&#x9;&#x9;'The unit symbol must be globally unique. Symbol collides with: ' + duplicateStr&#xA;&#x9;&#x9;,&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;Unit.allInstances()->excluding(self)->forAll(other | other.symbol &lt;> self.symbol)&#xA;&#x9;&#x9;&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="siUnitRef" eType="#//siUnitRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="siUnitRef" eSuperTypes="#//IPremiseObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="In case of a non SI unit the referenced unit contains the target unit and a conversion factor."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Unit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversionFactorFromSI"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AValueDef" abstract="true" eSuperTypes="#//IPremiseObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines a value. Base class for different types of Values. For this class, change notification will be omitted."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uncertainty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//AValueDef #//IOclValidated">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents the value of a parameter. In addition the value will be checked for correct content. For this model element, change notification is activated."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidNumber"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidNumber" value="Tuple {&#xA;&#x9;message : String = 'Value must be a valid real number',&#xA;&#x9;status : Boolean = value &lt;> null implies value.matches('^-?\\d*(\\d\\.|\\.\\d+)?([eE]-?\\d+)?$')&#xA;}.status"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Junction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A boolean description of a junction of two elements or relations."/>
    </eAnnotations>
    <eLiterals name="OR"/>
    <eLiterals name="AND" value="1"/>
    <eLiterals name="NOT" value="2"/>
    <eLiterals name="XOR" value="3"/>
    <eLiterals name="VOTE" value="4"/>
    <eLiterals name="PAND" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AParameterDef" abstract="true" eSuperTypes="#//ADataItem #//IMetaTypable PREMISE_Graph.ecore#//INode #//IQuantity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A parameter defines a configurable value of a system element."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//AParameterDef">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A constant defines a constant value of a system element like a physical constant."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaTypeDef" eSuperTypes="#//ADataItem">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Definition of a meta type. Includes the icons for a later representation."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconBase64" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="No icon integrated into registry. Enter path to icon here."/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOclValidated" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This interface provides the functionality to validate model elements."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AVersionedModelRoot" abstract="true"
      eSuperTypes="#//IPremiseObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="defines a version number for a model file independend of premise, usecase, registry or functionpool"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1.33" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Stores the version of the meta model as a string like 1.14."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMetaTypable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaTypes" upperBound="-1"
        eType="#//MetaTypeDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPremiseObject" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaData" ordered="false"
        upperBound="-1" eType="#//MetaData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IQuantity" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Interface for all elements with a unit like a parameter or requiered parameter."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//Unit"/>
  </eClassifiers>
</ecore:EPackage>
